version: '3.8'

services:
  garmin-workout-builder-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - GARMIN_CLIENT_ID=rafa.m.s@hotmail.com
      - GARMIN_CLIENT_SECRET=Familia@1224
